### ISSUE TITLE
[MAKIETA] Logowanie i rejestracja

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/specjalisci#10]

**Comment by AdamKowalczuk** [comment]
Zrobiłem ekran logowania i rejestracji w Figmie. 

Wersja desktop dostępna w zakładce "Gotowe widoki desktop", a wersja mobilna w zakładce "Gotowe widoki mobilne"

Link do figmy:
https://www.figma.com/file/ivAJJ3pWs1jM6SdtAYJOLG/Aplikacje-wielowarstwowe?type=design&node-id=0%3A1&mode=design&t=AanefCCSrH9onrp3-1
