### ISSUE TITLE
[BE] Properta z avatarem dla /api/search

### ISSUE THREAD

**Issue by maciek1651g** [MikolajczukKamil/specjalisci#123]
Do odpowiedzi z endpointu /api/serach trzeba dodać wartość z avatarem

**Comment by maslanypotwor** [comment]
PR już wystawiony: https://github.com/MikolajczukKamil/specjalisci/pull/142

**Comment by maslanypotwor** [comment]
Zmerdżowane - prośba o sprawdzenie na FE czy zaczytuje się ok.
