### ISSUE TITLE
Menu Profil nie działa jak się na niego wchodzi tuż po zarejestrowaniu

### ISSUE THREAD

**Issue by Kasia990518** [MikolajczukKamil/specjalisci#141]
Steps to reproduce:
1. Zarejestruj się używając dowolnych danych.
2. Zaloguj się używając danych podanych przy rejestracji
3. Przejdź do kraty Profil
![image](https://github.com/MikolajczukKamil/specjalisci/assets/97765208/998b9ca4-4da1-4c39-81ac-6d877379d09c)

**Comment by maslanypotwor** [comment]
Z poziomu testowania na lokalnym środowisku wszystko działa poprawnie - jeśli po wszystkich ostatnich poprawkach błąd będzie nadal występował podejrzewam ustawienia CORS.

**Comment by Kasia990518** [comment]
Retest ok
