### ISSUE TITLE
Numer telefonu nie zapisuje się na profilu

### ISSUE THREAD

**Issue by Kasia990518** [MikolajczukKamil/specjalisci#143]
Steps to reproduce:
1. Zaloguj się
2. Przejdź do karty Profil
3. Kliknij przycisk Edytuj
4. Wprowadź dane do pola Telefon
5. Kliknij Zapisz
6. Zaobserwuj rezultaty - wartość w polu Telefon zniknęła

**Comment by maslanypotwor** [comment]
Fix: https://github.com/MikolajczukKamil/specjalisci/pull/157

**Comment by maslanypotwor** [comment]
^ Fix zmerdżowany

**Comment by Kasia990518** [comment]
tested ok :)
