### ISSUE TITLE
Dodawanie komentarzy / ocen nie działa

### ISSUE THREAD

**Issue by Kasia990518** [MikolajczukKamil/specjalisci#148]
Steps to reproduce:

1. Zaloguj się
2. Wybierz dowolnego specjalistę z listy
3. Wystaw specjaliście dowolną ocenę i komentarz
4. Spróbuj zapisać

Zwraca 400 bad request: Request URL:https://95.217.193.230:9999/api/Rating

**Comment by maslanypotwor** [comment]
Ten PR rozwiązuje również problem z wystawianiem ratingu: https://github.com/MikolajczukKamil/specjalisci/pull/158
Błąd pojawia się dla nowo zarejestrowanych użytkowników którzy mieli puste profile.

**Comment by Kasia990518** [comment]
tested not ok - lista specjalistów jest pusta

**Comment by maslanypotwor** [comment]
Prawdopodobnie niekompatybilność frontu z nową opcją wyszukiwania

**Comment by maslanypotwor** [comment]
Dodatkowo jeszcze nie została uaktualniona baza

**Comment by Kasia990518** [comment]
tested ok!
