### ISSUE TITLE
Nie można zamówić usługi

### ISSUE THREAD

**Issue by Kasia990518** [MikolajczukKamil/specjalisci#149]
Steps to reproduce:

1. Zaloguj się dowolnym klientem
2. Kliknij Zamów usługę
3. Wypełnij pola z datą i opisem usługi
4. Spróbuj zatwierdzić - nic się nie dzieje

**Comment by maslanypotwor** [comment]
https://github.com/MikolajczukKamil/specjalisci/pull/101/files

Endpoint na zamówienie usługi

**Comment by maslanypotwor** [comment]
Endpoint zmerdżowany

**Comment by Kasia990518** [comment]
tested ok ;)
