### ISSUE TITLE
Profil dla nowego usera jest pusty

### ISSUE THREAD

**Issue by Kasia990518** [MikolajczukKamil/specjalisci#153]
Steps to reproduce:
1. Stwórz nowe konto
2. Zaloguj się wyżej swtorzonymi credentialami
3. Przejdź do zakładki Profil

![image](https://github.com/MikolajczukKamil/specjalisci/assets/97765208/fd3f63c3-085c-477a-8549-16ddf8512774)

**Comment by krzywo97** [comment]
czemu tam user id to -1?

**Comment by maslanypotwor** [comment]
@krzywo97 https://github.com/MikolajczukKamil/specjalisci/pull/119/files
To jest specjalna możliwość żeby endpoint zrozumiał, że chodzi o aktualnie zalogowanego użytkownika gdzie dane o użytkowniku bierzemy z tokenu. Tutaj PR który to wprowadził i dałeś approve.

**Comment by krzywo97** [comment]
Spoko, taki przemiał tych PRów był, że już zdążyłem zapomnieć 😆

**Comment by maslanypotwor** [comment]
https://github.com/MikolajczukKamil/specjalisci/pull/158

To powinno załatwić sprawę

**Comment by Kasia990518** [comment]
tested not ok :(

nadal pusty profil + lista specjalistów jest pusta xD 
![image](https://github.com/MikolajczukKamil/specjalisci/assets/97765208/4c026589-4d09-4820-af92-2aa9998dc393)

**Comment by Kasia990518** [comment]
tested ok!
