### ISSUE TITLE
Rejestracja wywala "wystąpił błąd" jeśli (prawdopodobnie) hasło jest za słabe

### ISSUE THREAD

**Issue by Kasia990518** [MikolajczukKamil/specjalisci#154]
Steps to reproduce:
1. Otwórz formularz rejestracji
2. Wypełnij formularz dowolnymi danymi - w polu hasło podaj "słabe" hasło, np. 12345678
3. Rezultat - "Wystąpił błąd", który niewiele mówi o tym czemu w zasadzie rejestracja się nie powiodła
![image](https://github.com/MikolajczukKamil/specjalisci/assets/97765208/6d3f61f5-2f68-4afe-9118-e0d52638a04f)

**Comment by maslanypotwor** [comment]
https://github.com/MikolajczukKamil/specjalisci/pull/159

To powinno załatwić sprawę

**Comment by Kasia990518** [comment]
Błąd nadal występuje :(

**Comment by Kasia990518** [comment]
tested ok :)
