### ISSUE TITLE
[CI/CD] Backend pierwsza wersja

### ISSUE THREAD

**Issue by aleksrosz** [MikolajczukKamil/specjalisci#18]
Cześć w celu utworzenia CI/CD dla backendu potrzebuje informację w jaki sposób mam zbudować projekt.

**Comment by aleksrosz** [comment]
@maslanypotwor @maciek1651g @krzywo97 proszę o odpowiedź

**Comment by simplymisfit** [comment]
Możesz rozwinąć co dokładnie potrzebujesz, jakie informacje?
@aleksrosz

**Comment by aleksrosz** [comment]
Jak zbudować obraz w dockerze. Jak ma wyglądać Dockerfile

**Comment by simplymisfit** [comment]
Niezbyt się znam na dockerze, bo nie miałem potrzeby skorzystać, ale w pracy mi powiedzieli, że żeby wygenerować dockerfile trzeba dać PPM na projekt w Visual Studio i będzie coś z tym związanego. Jakby nikt z BE tego nie ogarnął dzisiaj do 21, to ja spróbuję ogarnąć i podesłać. O ile o to oczywiście chodzi

**Comment by maslanypotwor** [comment]
Zrobiłem przykładowego Dockerfile'a: https://github.com/MikolajczukKamil/specjalisci/compare/dockerfile-example

Coś specyficznego dla .NET'u to konfiguracja jak zmusić aplikację do działania poza localhost'em kontenera. Z jakiegoś powodu mogę curlować adresy wewnątrz kontenera ale nie mogłem znaleźć sposobu jak zmusić tą aplikację do wypchnięcia komunikacji poza kontener (expose portów z poziomu dockerfile'a nie pomogły). Może ktoś kto robi w .NET'cie w pracy będzie wiedział o co chodzi.
