### ISSUE TITLE
[CI/CD] Frontend pierwsza wersja

### ISSUE THREAD

**Issue by aleksrosz** [MikolajczukKamil/specjalisci#19]
Cześć w celu utworzenia CI/CD dla frontendu potrzebuje informację w jaki sposób mam zbudować projekt.

**Comment by aleksrosz** [comment]
@maciek1651g proszę o odpowiedź

**Comment by maciek1651g** [comment]
W folderze z frontem jest plik README w którym jest opisane jak się buduje. Podlinkowałbym ale coś github nie działa.
Jak masz środowisko z Nodem i npm to polecenia do: instalowania paczek paczek: `npm install`, a zbudowanie: `npm run build`

**Comment by aleksrosz** [comment]
Spróbowałem tak:
Dockerfile:
FROM node:lts-iron
WORKDIR /app
COPY . .
RUN npm install -g @angular/cli@16.2.7
CMD ["ng serve", "src/index.js"]
EXPOSE 4200


node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/app/ng serve'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.9.0

Czy mógłbyś podpowiedzieć jak to powinno być?

**Comment by MikolajczukKamil** [comment]
Build można zrobić tak:
0. Instalujemy nodejs z npm, to obraz node:lts-iron ma
1. Pobieramy kod źródłowy z repo 
2. Instalujemy zależności z użyciem `npm ci`, (odpowiednik npm install tylko bez podbijania zależności, zainstalouje dokładnie to co w package-lock, przez to ewentualne błędy można odwtorzyć lokalnie z 100% pewnością tych samych wersji zależności)
3. Teraz z kodu źródłowego chcemy wygenerować pliki statyczne czyli .html .js .css, to robimy przez `npx ng build --configuration production`, (npx to polecenie do używania lokalnie zainstalowanych paczek czyli tych z punktu 2. użycie samego ng build też jest poprawne ale będzie wymagać globalnej instalacji pakietu a nie ma po co to robić)
4. W katalogu dist/NAZWA_PROJEKTU będą gotowe pliki statyczne trzeba jest zaserwować na ścieżce '/'

PS. npm serve stawia lokalne środowisko deweloperskie czyli stawia lokalny serwer na którym serwuje zbudowane pliki, buduje projekt jak i śledzi zmiany i przebudowuje go na żywo, jak deploujemy aplikację (nawet na testowe środowisko) nie powinniśmy już z tego korzystać.

lokalnie zbudowałem aplikację i pliki wyglądają następująco
![build](https://github.com/MikolajczukKamil/specjalisci/assets/25321219/afda3a5c-4d49-4b40-a09b-5e0507b6c4a5)

**Comment by MikolajczukKamil** [comment]
W skrócie:

```
RUN npm ci
RUN npx ng build --configuration production

# teraz zbudowane pliki z `dist/help-hunter-ui` chcemy upublicznić np za pomocą nginx
# jakoś na nowy obraz będzie trzeba to przesłać albo połączyć je tak aby nginx był dostępny (nie znam się na tym)
# COPY dist/help-hunter-ui /usr/share/nginx/html
```

**Comment by aleksrosz** [comment]
FROM node:lts-iron
WORKDIR /app
COPY . .
RUN npm ci
RUN npx ng build --configuration production
RUN npm run
EXPOSE 8080 


STEP 5/7: RUN npx ng build --configuration production
Error: /app/src/app/map/map-localisation/map-localisation.component.css exceeded maximum budget. Budget 4.00 kB was not met by 30.81 kB with a total of 34.81 kB.
Error: building at STEP "RUN npx ng build --configuration production": while running runtime: exit status 1
