### ISSUE TITLE
Poprawki makiet

### ISSUE THREAD

**Issue by MikolajczukKamil** [MikolajczukKamil/specjalisci#42]
Chcemy nieco zmienić wybór specjalizacji

![image](https://github.com/MikolajczukKamil/specjalisci/assets/25321219/6ad06233-66e6-41c7-b184-ddd7c91c9c5f)

1. Specjalizacje/usługi
- wyrzucamy tryb pracy przy osobie (będzie w usłudze)
- Specjalizacje zmieniamy na usługi (tytuł)
- Jak nie ma żadnej specjalizacji to mamy tylko ikonę + (dodaj) która umożliwia dodanie nowej usługi do profilu (w jakimś popupie)
- W tworzeniu usługi (ten popup) wybieramy kategorię następnie rodzaj usługi https://github.com/MikolajczukKamil/specjalisci/issues/41 np. Budowlanka a potem płytki, następnie podajemy cenę min i max, tryb wykonania (stac/dojazd) i opis
- Lista usług niech będzie grupowana per kategoria mniej więcej jak na "makiecie" z excela

2. Awatar
Awatar miał być wybierany z listy dostępnych jak w rejestracji (bez własnych zdjęć)

3. Tryb specjalisty 
Wajcha pokazuje że jesteśmy specjalistą
pojawia się wtedy: opis firmy oraz lista usług

**Comment by AdamKowalczuk** [comment]
@MikolajczukKamil Wgraliśmy zmiany na Figmie

**Comment by MikolajczukKamil** [comment]
@AdamKowalczuk 
1. Pierwsza makieta to chyba stara, może są gdzie przenieść/wyszarzyć/usunąć aby nie myliła
2. W Edycji/tworzeniu usługi, nie ma nazwy, za nazwę robi rodzaj usługi bo to będzie np. 'Układanie płytek', nie chcemy tego aby te same rzeczy były różnie nazywane
3. Lista, tu nam chodziło o właśnie listę, tak mniej więcej jak na excelu dołączonym, aby było widać nie tylko nazwę ale też inne informacje + jak kategoria jest pusta np mechanicy to jej nie ma po prostu. Dodawanie tylko na końcu, jaka to kategoria wybieramy w selekcie więc wystarczy jeden przycisk dodaj
4. Ten przycisk wajcha jakiś taki dziwny jest, możę by dać taki większy przycisk z napisem "Zostań specjalistą" lub wyszarzony (nie zachęcający do kliknięcia) "Zamknij profil specjalisty", to wiadomo drobna estetyczna uwaga
